version: '3.8'

services:
    mysql:
        container_name: multicambios_mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: multicambios
            MYSQL_USER: multicambios
            MYSQL_PASSWORD: multicambios
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
    redis:
        container_name: multicambios_redis
        image: redis:latest
        ports:
            - "6379:6379"

volumes:
    mysql_data:
